export enum OperationType {
  CONTAINS = 'CONTAINS',
  DOES_NOT_CONTAIN = 'DOES_NOT_CONTAIN',
  STARTS_WITH = 'STARTS_WITH',
  ENDS_WITH = 'ENDS_WITH',
  IS = 'IS',
  IS_NOT = 'IS_NOT',
  IS_EMPTY = 'IS_EMPTY',
  IS_NOT_EMPTY = 'IS_NOT_EMPTY',
  EQUAL = 'EQUAL',
  NOT_EQUAL = 'NOT_EQUAL',
  IN = 'IN',
  NOT_IN = 'NOT_IN',
  ANY_OF = 'ANY_OF',
  ALL_OF = 'ALL_OF',
  NONE_OF = 'NONE_OF',
  BIGGER_THAN = 'BIGGER_THAN',
  LOWER_THAN = 'LOWER_THAN',
  BIGGER_OR_EQUAL_THAN = 'BIGGER_OR_EQUAL_THAN',
  LOWER_OR_EQUAL_THAN = 'LOWER_OR_EQUAL_THAN',
  BEFORE = 'BEFORE',
  AFTER = 'AFTER',
  ON_OR_BEFORE = 'ON_OR_BEFORE',
  ON_OR_AFTER = 'ON_OR_AFTER',
  BETWEEN = 'BETWEEN',
  IS_ANY = 'IS_ANY',
}

export const defaultOperationLabels: Record<OperationType, string> = {
  AFTER: 'after',
  ALL_OF: 'all of',
  ANY_OF: 'any of',
  BIGGER_OR_EQUAL_THAN: '>=',
  BIGGER_THAN: '>',
  BEFORE: 'before',
  LOWER_OR_EQUAL_THAN: '<=',
  LOWER_THAN: '<',
  BETWEEN: 'between',
  CONTAINS: 'contains',
  DOES_NOT_CONTAIN: 'does not contain',
  EQUAL: '=',
  ENDS_WITH: 'ends with',
  IN: 'in',
  IS: 'is',
  IS_EMPTY: 'is empty',
  IS_NOT: 'is not',
  IS_NOT_EMPTY: 'is not empty',
  NONE_OF: 'none of',
  NOT_IN: 'not in',
  NOT_EQUAL: '!=',
  ON_OR_AFTER: 'on or after',
  ON_OR_BEFORE: 'on or before',
  STARTS_WITH: 'starts with',
  IS_ANY: 'is any',
};

export const defaultNoValueOperations = [
  OperationType.IS_EMPTY,
  OperationType.IS_NOT_EMPTY,
  OperationType.IS_ANY,
];

export const defaultTypeOperationsMap: Record<
  string,
  OperationType[]
> = {
  string: [
    OperationType.CONTAINS,
    OperationType.DOES_NOT_CONTAIN,
    OperationType.STARTS_WITH,
    OperationType.ENDS_WITH,
    OperationType.IS,
    OperationType.IS_NOT,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  number: [
    OperationType.EQUAL,
    OperationType.NOT_EQUAL,
    OperationType.BIGGER_OR_EQUAL_THAN,
    OperationType.BIGGER_THAN,
    OperationType.LOWER_OR_EQUAL_THAN,
    OperationType.LOWER_THAN,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  boolean: [
    OperationType.IS,
    OperationType.IS_NOT,
    OperationType.IS_ANY,
  ],
  date: [
    OperationType.IS,
    OperationType.BEFORE,
    OperationType.AFTER,
    OperationType.ON_OR_BEFORE,
    OperationType.ON_OR_AFTER,
    OperationType.BETWEEN,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  datetime: [
    OperationType.IS,
    OperationType.BEFORE,
    OperationType.AFTER,
    OperationType.ON_OR_BEFORE,
    OperationType.ON_OR_AFTER,
    OperationType.BETWEEN,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  time: [
    OperationType.IS,
    OperationType.BEFORE,
    OperationType.AFTER,
    OperationType.BETWEEN,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  select: [
    OperationType.IS,
    OperationType.IS_NOT,
    OperationType.IN,
    OperationType.NOT_IN,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  multiselect: [
    OperationType.ANY_OF,
    OperationType.ALL_OF,
    OperationType.NONE_OF,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  currency: [
    OperationType.EQUAL,
    OperationType.NOT_EQUAL,
    OperationType.BIGGER_OR_EQUAL_THAN,
    OperationType.BIGGER_THAN,
    OperationType.LOWER_OR_EQUAL_THAN,
    OperationType.LOWER_THAN,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  percent: [
    OperationType.EQUAL,
    OperationType.NOT_EQUAL,
    OperationType.BIGGER_OR_EQUAL_THAN,
    OperationType.BIGGER_THAN,
    OperationType.LOWER_OR_EQUAL_THAN,
    OperationType.LOWER_THAN,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  duration: [
    OperationType.EQUAL,
    OperationType.NOT_EQUAL,
    OperationType.BIGGER_OR_EQUAL_THAN,
    OperationType.BIGGER_THAN,
    OperationType.LOWER_OR_EQUAL_THAN,
    OperationType.LOWER_THAN,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  email: [
    OperationType.IS,
    OperationType.IS_NOT,
    OperationType.CONTAINS,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
  id: [
    OperationType.IS,
    OperationType.IS_NOT,
    OperationType.IN,
    OperationType.NOT_IN,
    OperationType.IS_EMPTY,
    OperationType.IS_NOT_EMPTY,
  ],
};

export const mapOperationToSelectOption = (
  operation: OperationType,
  operationLabels: Record<OperationType, string>
) => ({
  value: operation,
  label: operationLabels[operation],
});
